# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build using Maven Shade
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14 for x64
      uses: actions/setup-java@v1
      with:
        java-version: 14
        architecture: x64
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Package with Maven
      run: mvn clean package
    - name: Archive Packaged Jar
      uses: actions/upload-artifact@v2
      with:
        name: amongusplus.jar
        path: target/amongusplus.jar
      
  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: amongusplus.jar
        path: target/amongusplus.jar
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.5.7
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "among-us-plus-bot"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        buildpack: "https://github.com/heroku/heroku-buildpack-java.git"
